version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raul

  dbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    ports:
      - 8080:8978
