version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${PG_DATABASE}'
      POSTGRES_USER: '${PG_USERNAME}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'

  # dbeaver:
  #   image: dbeaver/cloudbeaver
  #   restart: always
  #   ports:
  #     - 8080:8978
